/**
 * Gallery from @thepaintedheritage
 * Landscapes -> sliding view
 * Portraits  -> grid (default 9+)
 */
window.KALAMKARI_WORKS = [
  /* ─── LANDSCAPE SLIDER — art only (no text overlays) ─── */
  {
    id: "land-srinivasa-master",
    title: "Srinivasa Kalyanam",
    type: "image",
    media: "assets/gallery/landscape/01-srinivasa-master.jpg",
    orientation: "landscape",
    featured: true,
    highRes: true,
    category: "mythic",
    size: "Large",
    medium: "Traditional Kalamkari | hand-painted on canvas",
    description:
      "Master canvas of the divine wedding - ceremony, ornament, and devotion across the full scene.",
    tags: ["srinivasa", "mythic", "sacred", "landscape"],
    instagramUrl: "https://www.instagram.com/thepaintedheritage/",
    objectPosition: "center center",
  },
  {
    id: "land-srinivasa-studio",
    title: "Srinivasa Kalyanam | Close detail",
    type: "image",
    media: "assets/gallery/landscape/04-srinivasa-studio.jpg",
    orientation: "landscape",
    category: "mythic",
    size: "Small",
    medium: "Hand-painted canvas",
    description:
      "Close view of a finished Srinivasa canvas: texture, dye, and freehand kalam line.",
    tags: ["srinivasa", "studio", "landscape"],
    instagramUrl: "https://www.instagram.com/p/DZ7nzYwjSlw/",
    objectPosition: "center center",
  },
  {
    id: "land-srinivasa-detail",
    title: "Srinivasa Kalyanam | Ornament",
    type: "image",
    media: "assets/gallery/landscape/05-srinivasa-detail.jpg",
    orientation: "landscape",
    category: "mythic",
    size: "Small",
    medium: "Traditional Kalamkari",
    description:
      "Jewel tones, arches, and sacred figures - pure painting, free of text.",
    tags: ["srinivasa", "detail", "landscape"],
    instagramUrl: "https://www.instagram.com/reel/DZxa1cozWRE/",
    objectPosition: "center center",
  },
  {
    id: "land-srinivasa-custom",
    title: "Srinivasa Kalyanam | Cloth work",
    type: "image",
    media: "assets/gallery/landscape/06-srinivasa-custom.jpg",
    orientation: "landscape",
    category: "mythic",
    size: "Large",
    medium: "Hand-painted Kalamkari canvas",
    description:
      "Full ceremonial composition on cloth, tailored for the collector's wall.",
    tags: ["srinivasa", "custom", "landscape"],
    instagramUrl: "https://www.instagram.com/reel/Dao48bnRnDz/",
    objectPosition: "center center",
  },
  {
    id: "land-pattabhishekam",
    title: "Srirama Pattabhishekam",
    type: "image",
    media: "assets/gallery/landscape/07-pattabhishekam.jpg",
    orientation: "landscape",
    category: "mythic",
    size: "Large",
    medium: "Traditional Kalamkari on canvas",
    description:
      "Coronation of Rama - pure painted figures, no overlay text.",
    tags: ["rama", "mythic", "landscape"],
    instagramUrl: "https://www.instagram.com/p/DaYDH7nz6nQ/",
    objectPosition: "center 30%",
  },
  {
    id: "land-ganesha",
    title: "Ganesha",
    type: "image",
    media: "assets/gallery/landscape/08-ganesha.jpg",
    orientation: "landscape",
    category: "sacred",
    size: "Medium",
    medium: "Hand-painted Kalamkari",
    description:
      "Lord Ganesha - auspicious form painted for home and mandir.",
    tags: ["ganesha", "sacred", "landscape"],
    instagramUrl: "https://www.instagram.com/reel/DaAv0mPtePE/",
    objectPosition: "center center",
  },
  {
    id: "land-tapestry",
    title: "Sacred trio detail",
    type: "image",
    media: "assets/gallery/landscape/09-tapestry.jpg",
    orientation: "landscape",
    category: "mythic",
    size: "Small",
    medium: "Hand-painted textile art",
    description:
      "Fine line and colour on canvas - a close study of divine presence.",
    tags: ["mythic", "detail", "landscape"],
    instagramUrl: "https://www.instagram.com/thepaintedheritage/",
    objectPosition: "center center",
  },

  /* ─── PORTRAIT (grid, default 9+) ─── */
  {
    id: "ig-DaYDH7nz6nQ",
    title: "Srirama Pattabhishekam",
    type: "image",
    media: "assets/gallery/ig/07-DaYDH7nz6nQ.jpg",
    orientation: "portrait",
    category: "mythic",
    size: "Medium",
    medium: "Traditional Kalamkari on canvas",
    description:
      "Lord Rama, Sita Devi, Lakshmana, and Hanuman - a radiant coronation of justice and harmony.",
    tags: ["rama", "mythic", "canvas", "sacred"],
    instagramUrl: "https://www.instagram.com/p/DaYDH7nz6nQ/",
    objectPosition: "center 18%",
  },
  {
    id: "ig-DaZPPB2TBaJ",
    title: "Srinivasa Kalyanam",
    type: "image",
    media: "assets/gallery/ig/06-DaZPPB2TBaJ.jpg",
    orientation: "portrait",
    category: "mythic",
    size: "Medium",
    medium: "Hand-painted Kalamkari",
    description:
      "Divine wedding of Lord Venkateswara and Padmavati - tradition and devotion for your wall.",
    tags: ["srinivasa", "mythic", "home", "sacred"],
    instagramUrl: "https://www.instagram.com/reel/DaZPPB2TBaJ/",
    objectPosition: "center 20%",
  },
  {
    id: "ig-DaFiCsVz8vm",
    title: "Srinivasa Kalyanam | Available",
    type: "image",
    media: "assets/gallery/ig/09-DaFiCsVz8vm.jpg",
    orientation: "portrait",
    category: "mythic",
    size: "Medium",
    medium: "Traditional Kalamkari | natural dyes",
    description:
      "A timeless sacred union - rich colour, fine line, and temple-story atmosphere.",
    tags: ["srinivasa", "mythic", "available"],
    instagramUrl: "https://www.instagram.com/reel/DaFiCsVz8vm/",
    objectPosition: "center 22%",
  },
  {
    id: "ig-DZ7nzYwjSlw",
    title: "Srinivasa Kalyanam | Studio",
    type: "image",
    media: "assets/gallery/ig/11-DZ7nzYwjSlw.jpg",
    orientation: "portrait",
    category: "mythic",
    size: "Medium",
    medium: "Hand-painted Kalamkari canvas",
    description:
      "Fresh from the atelier - painted texture and living colour of a finished canvas.",
    tags: ["srinivasa", "studio", "mythic"],
    instagramUrl: "https://www.instagram.com/p/DZ7nzYwjSlw/",
    objectPosition: "center center",
  },
  {
    id: "ig-DZxa1cozWRE",
    title: "Srinivasa Kalyanam | Detail",
    type: "image",
    media: "assets/gallery/ig/12-DZxa1cozWRE.jpg",
    orientation: "portrait",
    category: "mythic",
    size: "Medium",
    medium: "Traditional Kalamkari",
    description:
      "Ornament, jewel tones, and sacred figures from the Tirupati - Sri Kalahasti tradition.",
    tags: ["srinivasa", "mythic", "detail"],
    instagramUrl: "https://www.instagram.com/reel/DZxa1cozWRE/",
    objectPosition: "center 15%",
  },
  {
    id: "ig-Dao48bnRnDz",
    title: "Srinivasa Kalyanam | Custom",
    type: "image",
    media: "assets/gallery/ig/02-Dao48bnRnDz.jpg",
    orientation: "portrait",
    category: "mythic",
    size: "Large",
    medium: "Hand-painted Kalamkari canvas",
    description:
      "Custom Srinivasa Kalyanam, made to the collector's wall, size, and devotion.",
    tags: ["srinivasa", "custom", "mythic"],
    instagramUrl: "https://www.instagram.com/reel/Dao48bnRnDz/",
    objectPosition: "center 18%",
  },
  {
    id: "ig-DaAv0mPtePE",
    title: "Ganesha",
    type: "image",
    media: "assets/gallery/ig/10-DaAv0mPtePE.jpg",
    orientation: "portrait",
    category: "sacred",
    size: "Medium",
    medium: "Hand-painted Kalamkari",
    description:
      "Lord Ganesha - gentle presence painted with traditional line and colour.",
    tags: ["ganesha", "sacred", "mythic"],
    instagramUrl: "https://www.instagram.com/reel/DaAv0mPtePE/",
    objectPosition: "center 20%",
  },
  {
    id: "ig-DaiS_RRTii4",
    title: "The Ramayana - Through Sita's Eyes",
    type: "image",
    media: "assets/gallery/ig/04-DaiS_RRTii4.jpg",
    orientation: "portrait",
    category: "narrative",
    size: "Large",
    medium: "Traditional Kalamkari storytelling",
    description:
      "A timeless Ramayana vision - layered motifs and sacred narrative.",
    tags: ["ramayana", "sita", "narrative", "mythic"],
    instagramUrl: "https://www.instagram.com/reel/DaiS_RRTii4/",
    objectPosition: "center 12%",
  },
  {
    id: "ig-Dar9K9ORmSA",
    title: "Sundarakanda | In progress",
    type: "image",
    media: "assets/gallery/ig/01-Dar9K9ORmSA.jpg",
    orientation: "portrait",
    category: "process",
    size: "Medium",
    medium: "Kalamkari pen & colour on canvas",
    description:
      "Sundarakanda taking shape - epic story emerging stroke by stroke.",
    tags: ["sundarakanda", "process", "mythic"],
    instagramUrl: "https://www.instagram.com/reel/Dar9K9ORmSA/",
    objectPosition: "center 15%",
  },
  {
    id: "ig-DaYQsiETO6G",
    title: "Sundarakanda | Studio",
    type: "image",
    media: "assets/gallery/ig/05-DaYQsiETO6G.jpg",
    orientation: "portrait",
    category: "process",
    size: "Medium",
    medium: "Kalamkari on canvas",
    description:
      "Further progress on Sundarakanda - fine outline and the living hand of the kalam.",
    tags: ["sundarakanda", "process", "studio"],
    instagramUrl: "https://www.instagram.com/reel/DaYQsiETO6G/",
    objectPosition: "center 18%",
  },
  {
    id: "ig-DaktUt3zR83",
    title: "Gajendra Moksham | In progress",
    type: "image",
    media: "assets/gallery/ig/03-DaktUt3zR83.jpg",
    orientation: "portrait",
    category: "narrative",
    size: "Medium",
    medium: "Traditional Kalamkari",
    description:
      "Gajendra Moksham taking form - sacred rescue story painted with devotion.",
    tags: ["gajendra", "narrative", "process", "sacred"],
    instagramUrl: "https://www.instagram.com/reel/DaktUt3zR83/",
    objectPosition: "center 16%",
  },
  {
    id: "ig-DaNy879Ny3Y",
    title: "Beauty of Line",
    type: "image",
    media: "assets/gallery/ig/08-DaNy879Ny3Y.jpg",
    orientation: "portrait",
    category: "process",
    size: "Small",
    medium: "Hand-drawn Kalamkari line work",
    description:
      "Where the kalam begins - fine black outlines that give every motif its soul.",
    tags: ["line art", "process", "studio"],
    instagramUrl: "https://www.instagram.com/reel/DaNy879Ny3Y/",
    objectPosition: "center 25%",
  },
  {
    id: "seetha-srama",
    title: "Seetha & Rama - Sacred Scroll",
    type: "image",
    media: "assets/gallery/01-seetha-srama.jpg",
    orientation: "portrait",
    category: "mythic",
    size: "Large",
    medium: "Kalamkari on canvas",
    description:
      "Richly detailed sacred narrative - layered motifs and classic storytelling style.",
    tags: ["rama", "sita", "mythic", "narrative"],
    instagramUrl: "https://www.instagram.com/thepaintedheritage/",
    objectPosition: "center 20%",
  },
  {
    id: "fabric-close",
    title: "Heritage Cloth Close-up",
    type: "image",
    media: "assets/gallery/10-fabric-close.jpg",
    orientation: "portrait",
    category: "floral",
    size: "Small",
    medium: "Hand-painted textile art",
    description:
      "Intricate florals, borders, and dye depth that reward a closer look.",
    tags: ["floral", "detail", "textile"],
    instagramUrl: "https://www.instagram.com/thepaintedheritage/",
    objectPosition: "center center",
  },
  {
    id: "map-poster",
    title: "Painted Heritage Map",
    type: "image",
    media: "assets/gallery/03-map-poster.jpg",
    orientation: "portrait",
    category: "narrative",
    size: "Large",
    medium: "Kalamkari illustration on canvas",
    description:
      "Cartographic storytelling - geography, myth, and ornament on one surface.",
    tags: ["narrative", "map", "statement"],
    instagramUrl: "https://www.instagram.com/thepaintedheritage/",
    objectPosition: "center 10%",
  },
  {
    id: "lace-border",
    title: "Ornamental Border Lace",
    type: "image",
    media: "assets/gallery/12-lace-border.jpg",
    orientation: "portrait",
    category: "floral",
    size: "Small",
    medium: "Kalamkari ornamental painting",
    description:
      "Fine lace-like borders and repeating florals of the Kalamkari vocabulary.",
    tags: ["floral", "border", "ornament"],
    instagramUrl: "https://www.instagram.com/thepaintedheritage/",
    objectPosition: "center 30%",
  },
  {
    id: "studio-work",
    title: "Studio Canvas",
    type: "image",
    media: "assets/gallery/11-studio-work.jpg",
    orientation: "portrait",
    category: "process",
    size: "Medium",
    medium: "Hand-painted Kalamkari canvas",
    description:
      "Authentic process energy and living texture from the studio floor.",
    tags: ["studio", "process", "canvas"],
    instagramUrl: "https://www.instagram.com/thepaintedheritage/",
    objectPosition: "center center",
  },
];
